#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
#. /etc/X11/Xsession

sudo xset s off
sudo xset -dpms
sudo xset s noblank 

cd /home/pi
sudo jre-13.0.1/bin/java -jar Desktop/v1.jar
